version: "3.9"
services:
  api-gateway:
    build: ./api-gateway/
    ports:
      - "8070:8070"
  rabbitmq:
    build: ./rabbitmq/
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  songs_microservice:
    build: ./songs-microservice/
    ports:
      - "8060:8060"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
  history_microservice:
    build: ./history-microservice/
    ports:
      - "8090:8090"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
  database:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - database:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  database: