version: "3.9"
services:
  api-gateway:
    build: ./api-gateway/
    ports:
      - "8070:8070"
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  songs-microservice:
    build: ./songs-microservice/
    ports:
      - "8060:8060"
    depends_on:
      - rabbitmq
      - database
  history-microservice:
    build: ./history-microservice/
    ports:
      - "8090:8090"
    depends_on:
      - rabbitmq

  database:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - database:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  database: