name: Snyk

on:
  push:
    paths:
      - 'gateway/**'
      - '.github/workflows/snyk.yml'
    branches: [ "main" ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: marinastancu/frankensound:latest
        args: --severity-threshold=high
              --run-quality-checks=true  
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
